language: node_js
node_js:
- '0.10'
services: mongodb

deploy:
  strategy: git
  provider: heroku
  api_key:
    secure: VgYPTzrWd0yFXH3S7jLbCuOkxbyPVAfhUPWEofXqd7wyI/Vmvzg6Ls8y+jZIup9woi6ezf7vr+oxQGHzhXVKuB6thTHD0QlYBIhMb5X5qAxpzhDnFKS3PSUMla3ftIJkJqsvPLkMJGaO1+bsEOLeysfDHbQfWZr07i27yo/JL04=
  app: diario-tardin
  on:
    repo: 4lejandrito/diary
